/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/host": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get host status
         * @description Returns status and identity of the hypervisor host.
         */
        get: operations["getHost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get host capabilities
         * @description Feature discovery for UI, automation and agents. Clients must use this to know what the host supports instead of hardcoding assumptions.
         */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Checks only that the application process is alive. Always returns 200 while the process is up.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks that the application and the HypervisorProvider are ready to serve requests.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List storage pools */
        get: operations["listStoragePools"];
        put?: never;
        /**
         * Create a storage pool
         * @description Defines, builds and starts a new directory-based storage pool.
         *     The target directory is created if it does not exist.
         */
        post: operations["createStoragePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a storage pool */
        get: operations["getStoragePool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/pools/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a storage pool
         * @description Re-syncs the pool's volume list and usage numbers with the backing storage.
         */
        post: operations["refreshStoragePool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/isos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ISO images in the library
         * @description ISO images available as installation media. Backed by a dedicated
         *     directory on the host (ULTRAV_ISO_DIR). Files are uploaded via the
         *     browser with `uploadIso`.
         */
        get: operations["listIsos"];
        put?: never;
        /**
         * Upload an ISO image
         * @description Streams the file into the ISO library. The filename must end in `.iso`.
         */
        post: operations["uploadIso"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/isos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an ISO image
         * @description Removes the file from the ISO library.
         */
        delete: operations["deleteIso"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List virtual networks */
        get: operations["listNetworks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a virtual network */
        get: operations["getNetwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a virtual network */
        post: operations["startNetwork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/networks/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a virtual network
         * @description Stops the virtual network. Running VMs attached to it keep working but
         *     lose new DHCP leases and NAT until the network is started again.
         */
        post: operations["stopNetwork"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List virtual machines */
        get: operations["listVirtualMachines"];
        put?: never;
        /**
         * Create a virtual machine
         * @description Defines a new virtual machine: allocates a disk volume in the chosen
         *     storage pool and defines the domain (left stopped unless `start` is
         *     true). The VM is not booted from an OS image — attach installation
         *     media with virt-install/virt-manager afterwards if needed.
         */
        post: operations["createVirtualMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a virtual machine */
        get: operations["getVirtualMachine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a virtual machine
         * @description Powers on a stopped virtual machine. Returns 409 if already running.
         */
        post: operations["startVirtualMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{id}/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gracefully shut down a virtual machine
         * @description Sends an ACPI shutdown event. The guest OS should shut down cleanly.
         */
        post: operations["shutdownVirtualMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{id}/reboot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reboot a virtual machine
         * @description Sends an ACPI reboot event. Returns 409 if the VM is not running.
         */
        post: operations["rebootVirtualMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vms/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Force stop a virtual machine
         * @description Immediately powers off the VM, equivalent to pulling the power cable.
         *     The guest OS is not given a chance to shut down cleanly; data loss or
         *     filesystem corruption is possible. Prefer `shutdownVirtualMachine`.
         */
        post: operations["forceStopVirtualMachine"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @example VM_NOT_FOUND */
                code: string;
                /** @example Virtual machine was not found */
                message: string;
                /** @example req_01HV3M9Z2K */
                requestId: string;
            };
        };
        Host: {
            /** @example kvm01 */
            hostname: string;
            /** @example Ubuntu 24.04 LTS */
            operatingSystem: string;
            /** @example 6.8.0-45-generic */
            kernel: string;
            /** @example 128934 */
            uptimeSeconds: number;
            cpu: components["schemas"]["Cpu"];
            /**
             * Format: int64
             * @example 68719476736
             */
            memoryTotalBytes: number;
            /**
             * Format: int64
             * @example 21474836480
             */
            memoryUsedBytes: number;
            virtualization?: components["schemas"]["HostVirtualization"];
            /**
             * Format: int64
             * @example 2199023255552
             */
            storageTotalBytes?: number;
            /**
             * Format: int64
             * @example 789128484864
             */
            storageUsedBytes?: number;
            /** @example 8.2.0 */
            qemuVersion?: string;
            /** @example 10.0.0 */
            libvirtVersion?: string;
        };
        Cpu: {
            /** @example AMD EPYC 7402P 24-Core Processor */
            model: string;
            /** @example 24 */
            cores: number;
            /** @example 48 */
            threads: number;
            /**
             * Format: float
             * @example 23.5
             */
            usagePercent?: number;
        };
        HostVirtualization: {
            /** @example true */
            kvmEnabled?: boolean;
        };
        VirtualMachineList: {
            items: components["schemas"]["VirtualMachine"][];
            /** @example 4 */
            total: number;
        };
        Network: {
            /** @example default */
            id: string;
            /** @example default */
            name: string;
            /**
             * @example active
             * @enum {string}
             */
            state: "active" | "inactive";
            /** @example true */
            autostart: boolean;
            /** @example virbr0 */
            bridge?: string | null;
            /** @example 10.0.0.1 */
            ipAddress?: string | null;
            /** @example 24 */
            ipPrefix?: number | null;
            /** @example true */
            dhcpEnabled: boolean;
            /** @example default */
            domainName?: string | null;
        };
        NetworkList: {
            items: components["schemas"]["Network"][];
            /** @example 2 */
            total: number;
        };
        StoragePool: {
            /** @example default */
            id: string;
            /** @example default */
            name: string;
            /**
             * @example dir
             * @enum {string}
             */
            type: "dir" | "fs" | "netfs" | "lvm" | "disk" | "iscsi" | "zfs" | "rbd" | "other";
            /**
             * @example active
             * @enum {string}
             */
            state: "active" | "inactive";
            /** @example true */
            autostart?: boolean;
            /**
             * Format: int64
             * @example 2199023255552
             */
            capacityBytes: number;
            /**
             * Format: int64
             * @example 789128484864
             */
            allocationBytes: number;
            /**
             * Format: int64
             * @example 1409894770688
             */
            availableBytes: number;
            /** @example /var/lib/libvirt/images */
            targetPath?: string | null;
        };
        StoragePoolCreate: {
            /**
             * @description Same rules as resource ids (a-z0-9._-
             * @example iso-store
             */
            name: string;
            /**
             * @description Only directory pools are supported for now
             * @default dir
             * @example dir
             * @enum {string}
             */
            type: "dir";
            /**
             * @description Absolute host path; created if missing
             * @example /var/lib/libvirt/isos
             */
            targetPath: string;
            /**
             * @default true
             * @example true
             */
            autostart: boolean;
        };
        StoragePoolList: {
            items: components["schemas"]["StoragePool"][];
            /** @example 2 */
            total: number;
        };
        Health: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok";
        };
        Readiness: {
            /**
             * @example ready
             * @enum {string}
             */
            status: "ready" | "not-ready";
            /**
             * @example ready
             * @enum {string}
             */
            hypervisor: "ready" | "unavailable";
        };
        Capabilities: {
            virtualization: components["schemas"]["CapabilitiesVirtualization"];
            storage: components["schemas"]["CapabilitiesStorage"];
            features: components["schemas"]["CapabilitiesFeatures"];
        };
        CapabilitiesVirtualization: {
            kvm: boolean;
            uefi: boolean;
        };
        CapabilitiesStorage: {
            qcow2: boolean;
            raw: boolean;
            snapshots: boolean;
        };
        CapabilitiesFeatures: {
            /** @example false */
            backup: boolean;
            /** @example false */
            migration: boolean;
            /** @example false */
            cloudInit: boolean;
        };
        /**
         * @description - running: powered on and operational
         *     - stopped: powered off
         *     - shutting-down: graceful shutdown in progress
         *     - starting: power-on in progress
         * @enum {string}
         */
        VMState: "running" | "stopped" | "paused" | "shutting-down" | "starting" | "error";
        VirtualMachineCreate: {
            /** @example app01 */
            name: string;
            /** @example 2 */
            vcpus: number;
            /**
             * Format: int64
             * @example 4294967296
             */
            memoryBytes: number;
            disk: components["schemas"]["DiskCreate"];
            /** @example default */
            networkId?: string;
            /**
             * @description Optional ISO from the library to attach as install media (CD-ROM, first boot device).
             * @example ubuntu-24.04-live-server.iso
             */
            isoId?: string | null;
            /**
             * @description Power on immediately after creation.
             * @example false
             */
            start?: boolean;
        };
        DiskCreate: {
            /** @example default */
            poolId: string;
            /**
             * Format: int64
             * @example 42949672960
             */
            sizeBytes: number;
            /**
             * @example qcow2
             * @enum {string}
             */
            format?: "qcow2" | "raw";
        };
        Iso: {
            /** @example ubuntu-24.04-live-server.iso */
            id: string;
            /** @example ubuntu-24.04-live-server.iso */
            fileName: string;
            /**
             * Format: int64
             * @example 2197821440
             */
            sizeBytes: number;
            /**
             * Format: date-time
             * @example 2025-09-01T12:00:00Z
             */
            uploadedAt?: string;
        };
        IsoList: {
            items: components["schemas"]["Iso"][];
            /** @example 2 */
            total: number;
        };
        Disk: {
            /** @example vda */
            name: string;
            /**
             * @example qcow2
             * @enum {string}
             */
            format: "qcow2" | "raw";
            /**
             * Format: int64
             * @example 128849018880
             */
            sizeBytes: number;
            /**
             * @example virtio
             * @enum {string}
             */
            bus?: "virtio" | "sata" | "scsi";
        };
        NetworkInterface: {
            /** @example ens3 */
            name: string;
            /**
             * @example virtio
             * @enum {string}
             */
            model: "virtio" | "e1000" | "rtl8139";
            /** @example 52:54:00:a1:b2:c3 */
            macAddress?: string;
            /** @example 10.0.0.11 */
            ipAddress?: string;
            /** @example default */
            network?: string;
        };
        VirtualMachine: {
            /** @example erp01 */
            id: string;
            /** @example erp01 */
            name: string;
            state: components["schemas"]["VMState"];
            /** @example 4 */
            vcpus: number;
            /**
             * Format: int64
             * @example 8589934592
             */
            memoryBytes: number;
            /** @example 345600 */
            uptimeSeconds: number | null;
            /** @example Ubuntu 24.04 LTS */
            os?: string;
            /** @example 10.0.0.11 */
            ipAddress?: string | null;
            disks: components["schemas"]["Disk"][];
            networkInterfaces: components["schemas"]["NetworkInterface"][];
            /**
             * Format: date-time
             * @example 2025-09-01T12:00:00Z
             */
            bootTime?: string | null;
        };
    };
    responses: {
        /** @description Virtual machine not found */
        VMNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VM_NOT_FOUND",
                 *         "message": "Virtual machine was not found",
                 *         "requestId": "req_01HV3M9Z2K"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation not valid for the current VM state */
        VMInvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VM_INVALID_STATE",
                 *         "message": "Virtual machine is not running",
                 *         "requestId": "req_01HV3M9Z2L"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error (no internal details are exposed) */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INTERNAL_ERROR",
                 *         "message": "An internal error occurred",
                 *         "requestId": "req_01HV3M9Z2M"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Virtual machine identifier (name). */
        VMId: string;
        /** @description Resource identifier (libvirt name). */
        ResourceID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "hostname": "kvm01",
                     *       "operatingSystem": "Ubuntu 24.04 LTS",
                     *       "kernel": "6.8.0-45-generic",
                     *       "uptimeSeconds": 128934,
                     *       "cpu": {
                     *         "model": "AMD EPYC 7402P 24-Core Processor",
                     *         "cores": 24,
                     *         "threads": 48,
                     *         "usagePercent": 23.5
                     *       },
                     *       "memoryTotalBytes": 68719476736,
                     *       "memoryUsedBytes": 21474836480,
                     *       "virtualization": {
                     *         "kvmEnabled": true
                     *       },
                     *       "qemuVersion": "8.2.0",
                     *       "libvirtVersion": "10.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["Host"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Host capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "virtualization": {
                     *         "kvm": true,
                     *         "uefi": true
                     *       },
                     *       "storage": {
                     *         "qcow2": true,
                     *         "raw": true,
                     *         "snapshots": true
                     *       },
                     *       "features": {
                     *         "backup": false,
                     *         "migration": false,
                     *         "cloudInit": false
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ready",
                     *       "hypervisor": "ready"
                     *     }
                     */
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready (e.g. hypervisor provider unavailable) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "not-ready",
                     *       "hypervisor": "unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    listStoragePools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage pools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoragePoolList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createStoragePool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "iso-store",
                 *       "targetPath": "/var/lib/libvirt/isos",
                 *       "autostart": true
                 *     }
                 */
                "application/json": components["schemas"]["StoragePoolCreate"];
            };
        };
        responses: {
            /** @description Pool created (returns the pool) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoragePool"];
                };
            };
            /** @description Validation error (name/targetPath) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A pool with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "STORAGE_POOL_ALREADY_EXISTS",
                     *         "message": "A storage pool with this name already exists",
                     *         "requestId": "req_01HV3M9Z2K2Q"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getStoragePool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage pool details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoragePool"];
                };
            };
            /** @description Storage pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    refreshStoragePool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool refreshed (returns updated pool) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoragePool"];
                };
            };
            /** @description Storage pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listIsos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ISO images */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IsoList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    uploadIso: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description ISO uploaded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Iso"];
                };
            };
            /** @description Invalid file (must be a .iso file) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description An ISO with this filename already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    deleteIso: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ISO deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ISO not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listNetworks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual networks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getNetwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Network not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    startNetwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network started (returns updated network) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Network not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Network is already active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    stopNetwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource identifier (libvirt name). */
                id: components["parameters"]["ResourceID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network stopped (returns updated network) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Network"];
                };
            };
            /** @description Network not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Network is already inactive */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listVirtualMachines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual machines */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachineList"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    createVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "app01",
                 *       "vcpus": 2,
                 *       "memoryBytes": 4294967296,
                 *       "disk": {
                 *         "poolId": "default",
                 *         "sizeBytes": 42949672960,
                 *         "format": "qcow2"
                 *       },
                 *       "networkId": "default",
                 *       "start": false
                 *     }
                 */
                "application/json": components["schemas"]["VirtualMachineCreate"];
            };
        };
        responses: {
            /** @description Virtual machine created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            /** @description Invalid create specification */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description A virtual machine with this name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    getVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Virtual machine identifier (name). */
                id: components["parameters"]["VMId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Virtual machine details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            404: components["responses"]["VMNotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    startVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Virtual machine identifier (name). */
                id: components["parameters"]["VMId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VM started (returns updated VM) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            404: components["responses"]["VMNotFound"];
            409: components["responses"]["VMInvalidState"];
            500: components["responses"]["InternalError"];
        };
    };
    shutdownVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Virtual machine identifier (name). */
                id: components["parameters"]["VMId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shutdown requested (returns updated VM) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            404: components["responses"]["VMNotFound"];
            409: components["responses"]["VMInvalidState"];
            500: components["responses"]["InternalError"];
        };
    };
    rebootVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Virtual machine identifier (name). */
                id: components["parameters"]["VMId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reboot requested (returns updated VM) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            404: components["responses"]["VMNotFound"];
            409: components["responses"]["VMInvalidState"];
            500: components["responses"]["InternalError"];
        };
    };
    forceStopVirtualMachine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Virtual machine identifier (name). */
                id: components["parameters"]["VMId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description VM force stopped (returns updated VM) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VirtualMachine"];
                };
            };
            404: components["responses"]["VMNotFound"];
            409: components["responses"]["VMInvalidState"];
            500: components["responses"]["InternalError"];
        };
    };
}
