// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for BackupState.
const (
	Complete BackupState = "complete"
)

// Defines values for BackupType.
const (
	BackupTypeFull        BackupType = "full"
	BackupTypeIncremental BackupType = "incremental"
)

// Defines values for BackupCreateType.
const (
	BackupCreateTypeFull        BackupCreateType = "full"
	BackupCreateTypeIncremental BackupCreateType = "incremental"
)

// Defines values for BackupDiskFormat.
const (
	BackupDiskFormatQcow2 BackupDiskFormat = "qcow2"
	BackupDiskFormatRaw   BackupDiskFormat = "raw"
)

// Defines values for BackupScheduleType.
const (
	BackupScheduleTypeAuto        BackupScheduleType = "auto"
	BackupScheduleTypeFull        BackupScheduleType = "full"
	BackupScheduleTypeIncremental BackupScheduleType = "incremental"
)

// Defines values for BackupScheduleCreateType.
const (
	BackupScheduleCreateTypeAuto        BackupScheduleCreateType = "auto"
	BackupScheduleCreateTypeFull        BackupScheduleCreateType = "full"
	BackupScheduleCreateTypeIncremental BackupScheduleCreateType = "incremental"
)

// Defines values for BackupScheduleUpdateType.
const (
	Auto        BackupScheduleUpdateType = "auto"
	Full        BackupScheduleUpdateType = "full"
	Incremental BackupScheduleUpdateType = "incremental"
)

// Defines values for CreateUserRequestRole.
const (
	CreateUserRequestRoleAdmin  CreateUserRequestRole = "admin"
	CreateUserRequestRoleViewer CreateUserRequestRole = "viewer"
)

// Defines values for DiskBus.
const (
	DiskBusSata   DiskBus = "sata"
	DiskBusScsi   DiskBus = "scsi"
	DiskBusVirtio DiskBus = "virtio"
)

// Defines values for DiskFormat.
const (
	DiskFormatQcow2 DiskFormat = "qcow2"
	DiskFormatRaw   DiskFormat = "raw"
)

// Defines values for DiskCreateFormat.
const (
	Qcow2 DiskCreateFormat = "qcow2"
	Raw   DiskCreateFormat = "raw"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for NetworkMode.
const (
	NetworkModeBridge   NetworkMode = "bridge"
	NetworkModeIsolated NetworkMode = "isolated"
	NetworkModeNat      NetworkMode = "nat"
)

// Defines values for NetworkState.
const (
	NetworkStateActive   NetworkState = "active"
	NetworkStateInactive NetworkState = "inactive"
)

// Defines values for NetworkCreateMode.
const (
	NetworkCreateModeBridge   NetworkCreateMode = "bridge"
	NetworkCreateModeIsolated NetworkCreateMode = "isolated"
	NetworkCreateModeNat      NetworkCreateMode = "nat"
)

// Defines values for NetworkInterfaceModel.
const (
	NetworkInterfaceModelE1000   NetworkInterfaceModel = "e1000"
	NetworkInterfaceModelRtl8139 NetworkInterfaceModel = "rtl8139"
	NetworkInterfaceModelVirtio  NetworkInterfaceModel = "virtio"
)

// Defines values for NetworkUpdateMode.
const (
	Bridge   NetworkUpdateMode = "bridge"
	Isolated NetworkUpdateMode = "isolated"
	Nat      NetworkUpdateMode = "nat"
)

// Defines values for PerformanceProfileCache.
const (
	None PerformanceProfileCache = "none"
)

// Defines values for PerformanceProfileCpuMode.
const (
	Custom          PerformanceProfileCpuMode = "custom"
	HostModel       PerformanceProfileCpuMode = "host-model"
	HostPassthrough PerformanceProfileCpuMode = "host-passthrough"
)

// Defines values for PerformanceProfileDiskBus.
const (
	Sata PerformanceProfileDiskBus = "sata"
	Scsi PerformanceProfileDiskBus = "scsi"
)

// Defines values for PerformanceProfileNicModel.
const (
	PerformanceProfileNicModelE1000e  PerformanceProfileNicModel = "e1000e"
	PerformanceProfileNicModelRtl8139 PerformanceProfileNicModel = "rtl8139"
	PerformanceProfileNicModelVirtio  PerformanceProfileNicModel = "virtio"
)

// Defines values for ReadinessHypervisor.
const (
	ReadinessHypervisorReady       ReadinessHypervisor = "ready"
	ReadinessHypervisorUnavailable ReadinessHypervisor = "unavailable"
)

// Defines values for ReadinessStatus.
const (
	ReadinessStatusNotReady ReadinessStatus = "not-ready"
	ReadinessStatusReady    ReadinessStatus = "ready"
)

// Defines values for StoragePoolState.
const (
	StoragePoolStateActive   StoragePoolState = "active"
	StoragePoolStateInactive StoragePoolState = "inactive"
)

// Defines values for StoragePoolType.
const (
	StoragePoolTypeDir   StoragePoolType = "dir"
	StoragePoolTypeDisk  StoragePoolType = "disk"
	StoragePoolTypeFs    StoragePoolType = "fs"
	StoragePoolTypeIscsi StoragePoolType = "iscsi"
	StoragePoolTypeLvm   StoragePoolType = "lvm"
	StoragePoolTypeNetfs StoragePoolType = "netfs"
	StoragePoolTypeOther StoragePoolType = "other"
	StoragePoolTypeRbd   StoragePoolType = "rbd"
	StoragePoolTypeZfs   StoragePoolType = "zfs"
)

// Defines values for StoragePoolCreateType.
const (
	StoragePoolCreateTypeDir StoragePoolCreateType = "dir"
)

// Defines values for UserRole.
const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleViewer UserRole = "viewer"
)

// Defines values for VMState.
const (
	VMStateError        VMState = "error"
	VMStatePaused       VMState = "paused"
	VMStateRunning      VMState = "running"
	VMStateShuttingDown VMState = "shutting-down"
	VMStateStarting     VMState = "starting"
	VMStateStopped      VMState = "stopped"
)

// Defines values for VirtualMachineOsType.
const (
	VirtualMachineOsTypeLinux   VirtualMachineOsType = "linux"
	VirtualMachineOsTypeOther   VirtualMachineOsType = "other"
	VirtualMachineOsTypeWindows VirtualMachineOsType = "windows"
)

// Defines values for VirtualMachineCreateNicModel.
const (
	VirtualMachineCreateNicModelE1000e  VirtualMachineCreateNicModel = "e1000e"
	VirtualMachineCreateNicModelRtl8139 VirtualMachineCreateNicModel = "rtl8139"
	VirtualMachineCreateNicModelVirtio  VirtualMachineCreateNicModel = "virtio"
)

// Defines values for VirtualMachineCreateOsType.
const (
	VirtualMachineCreateOsTypeLinux   VirtualMachineCreateOsType = "linux"
	VirtualMachineCreateOsTypeOther   VirtualMachineCreateOsType = "other"
	VirtualMachineCreateOsTypeWindows VirtualMachineCreateOsType = "windows"
)

// Backup defines model for Backup.
type Backup struct {
	CreatedAt    time.Time    `json:"createdAt"`
	Disks        []BackupDisk `json:"disks"`
	HasDomainXml *bool        `json:"hasDomainXml,omitempty"`
	Id           string       `json:"id"`

	// ParentId For incremental points, the id of the backup this one continues from.
	ParentId *string `json:"parentId"`

	// SizeBytes Total size of the backup's disk images on the backup storage.
	SizeBytes int64        `json:"sizeBytes"`
	State     *BackupState `json:"state,omitempty"`

	// Type `full` copies every disk in full and resets the chain;
	// `incremental` copies only the blocks modified since the previous
	// point (requires a valid chain, i.e. the parent's checkpoint still
	// exists in the domain).
	Type   BackupType `json:"type"`
	VmId   string     `json:"vmId"`
	VmName string     `json:"vmName"`
}

// BackupState defines model for Backup.State.
type BackupState string

// BackupType `full` copies every disk in full and resets the chain;
// `incremental` copies only the blocks modified since the previous
// point (requires a valid chain, i.e. the parent's checkpoint still
// exists in the domain).
type BackupType string

// BackupCreate defines model for BackupCreate.
type BackupCreate struct {
	// Type Force the point type. `incremental` fails with 409
	// `BACKUP_INVALID_STATE` when no valid chain exists (e.g. after a
	// restore or if the parent checkpoint was deleted). Absent = auto
	// (incremental when a chain is valid, full otherwise).
	Type *BackupCreateType `json:"type,omitempty"`
}

// BackupCreateType Force the point type. `incremental` fails with 409
// `BACKUP_INVALID_STATE` when no valid chain exists (e.g. after a
// restore or if the parent checkpoint was deleted). Absent = auto
// (incremental when a chain is valid, full otherwise).
type BackupCreateType string

// BackupDisk defines model for BackupDisk.
type BackupDisk struct {
	File      string            `json:"file"`
	Format    *BackupDiskFormat `json:"format,omitempty"`
	Name      string            `json:"name"`
	SizeBytes int64             `json:"sizeBytes"`
}

// BackupDiskFormat defines model for BackupDisk.Format.
type BackupDiskFormat string

// BackupList defines model for BackupList.
type BackupList struct {
	Items []Backup `json:"items"`
	Total int      `json:"total"`
}

// BackupSchedule defines model for BackupSchedule.
type BackupSchedule struct {
	Enabled bool   `json:"enabled"`
	Id      string `json:"id"`

	// LastRun When the schedule last fired (null = never).
	LastRun *time.Time `json:"lastRun"`
	Name    string     `json:"name"`

	// RetentionKeepLast Number of full chains to keep (each chain = a full backup plus
	// the incrementals on top of it). 0 disables pruning.
	RetentionKeepLast int `json:"retentionKeepLast"`

	// Time Daily run time, server local time (HH:MM).
	Time string `json:"time"`

	// Type Point type policy applied on each run.
	Type BackupScheduleType `json:"type"`

	// VmIds Target VM names, or `["*"]` for every VM at run time.
	VmIds []string `json:"vmIds"`
}

// BackupScheduleType Point type policy applied on each run.
type BackupScheduleType string

// BackupScheduleCreate defines model for BackupScheduleCreate.
type BackupScheduleCreate struct {
	Enabled           *bool  `json:"enabled,omitempty"`
	Name              string `json:"name"`
	RetentionKeepLast *int   `json:"retentionKeepLast,omitempty"`

	// Time Daily run time, server local time (HH:MM).
	Time string                    `json:"time"`
	Type *BackupScheduleCreateType `json:"type,omitempty"`

	// VmIds Target VM names, or `["*"]` for every VM.
	VmIds []string `json:"vmIds"`
}

// BackupScheduleCreateType defines model for BackupScheduleCreate.Type.
type BackupScheduleCreateType string

// BackupScheduleList defines model for BackupScheduleList.
type BackupScheduleList struct {
	Items []BackupSchedule `json:"items"`
	Total int              `json:"total"`
}

// BackupScheduleUpdate Partial update; only present fields change (name/id immutable).
type BackupScheduleUpdate struct {
	Enabled           *bool                     `json:"enabled,omitempty"`
	RetentionKeepLast *int                      `json:"retentionKeepLast,omitempty"`
	Time              *string                   `json:"time,omitempty"`
	Type              *BackupScheduleUpdateType `json:"type,omitempty"`
	VmIds             *[]string                 `json:"vmIds,omitempty"`
}

// BackupScheduleUpdateType defines model for BackupScheduleUpdate.Type.
type BackupScheduleUpdateType string

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Features       CapabilitiesFeatures       `json:"features"`
	Storage        CapabilitiesStorage        `json:"storage"`
	Virtualization CapabilitiesVirtualization `json:"virtualization"`
}

// CapabilitiesFeatures defines model for CapabilitiesFeatures.
type CapabilitiesFeatures struct {
	Backup    bool `json:"backup"`
	CloudInit bool `json:"cloudInit"`
	Migration bool `json:"migration"`
}

// CapabilitiesStorage defines model for CapabilitiesStorage.
type CapabilitiesStorage struct {
	Qcow2     bool `json:"qcow2"`
	Raw       bool `json:"raw"`
	Snapshots bool `json:"snapshots"`
}

// CapabilitiesVirtualization defines model for CapabilitiesVirtualization.
type CapabilitiesVirtualization struct {
	Kvm  bool `json:"kvm"`
	Uefi bool `json:"uefi"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// Cpu defines model for Cpu.
type Cpu struct {
	Cores        int      `json:"cores"`
	Model        string   `json:"model"`
	Threads      int      `json:"threads"`
	UsagePercent *float32 `json:"usagePercent,omitempty"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Password string                `json:"password"`
	Role     CreateUserRequestRole `json:"role"`
	Username string                `json:"username"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// Disk defines model for Disk.
type Disk struct {
	Bus       *DiskBus   `json:"bus,omitempty"`
	Format    DiskFormat `json:"format"`
	Name      string     `json:"name"`
	SizeBytes int64      `json:"sizeBytes"`

	// UsedBytes Space currently allocated for this disk on the host (the backing volume's allocation, not the guest filesystem usage). Null when the hypervisor cannot report it.
	UsedBytes *int64 `json:"usedBytes"`
}

// DiskBus defines model for Disk.Bus.
type DiskBus string

// DiskFormat defines model for Disk.Format.
type DiskFormat string

// DiskCreate defines model for DiskCreate.
type DiskCreate struct {
	Format    *DiskCreateFormat `json:"format,omitempty"`
	PoolId    string            `json:"poolId"`
	SizeBytes int64             `json:"sizeBytes"`
}

// DiskCreateFormat defines model for DiskCreate.Format.
type DiskCreateFormat string

// Error defines model for Error.
type Error struct {
	Error struct {
		// Code Stable error identifier. Known values: VM_NOT_FOUND, VM_INVALID_STATE, VM_ALREADY_EXISTS, VALIDATION_ERROR, NOT_FOUND, METHOD_NOT_ALLOWED, STORAGE_POOL_NOT_FOUND, STORAGE_POOL_ALREADY_EXISTS, NETWORK_NOT_FOUND, NETWORK_INVALID_STATE, NETWORK_INACTIVE (a virtual network a VM references is not active — start it before powering on the VM), NETWORK_ALREADY_EXISTS, ISO_NOT_FOUND, ISO_ALREADY_EXISTS, UNAUTHORIZED, INVALID_CREDENTIALS, FORBIDDEN, USER_NOT_FOUND, USER_ALREADY_EXISTS, LAST_ADMIN, CONSOLE_UNAVAILABLE, STORAGE_UNAVAILABLE (the hypervisor cannot open a file the domain references), KVM_UNAVAILABLE (hardware virtualization missing or inaccessible on the host), BACKUP_NOT_FOUND, BACKUP_INVALID_STATE (the backup's VM is running or no longer exists — stop the VM first), SCHEDULE_NOT_FOUND, INTERNAL_ERROR.
		Code      string `json:"code"`
		Message   string `json:"message"`
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Host defines model for Host.
type Host struct {
	Cpu               Cpu                 `json:"cpu"`
	Hostname          string              `json:"hostname"`
	Kernel            string              `json:"kernel"`
	LibvirtVersion    *string             `json:"libvirtVersion,omitempty"`
	MemoryTotalBytes  int64               `json:"memoryTotalBytes"`
	MemoryUsedBytes   int64               `json:"memoryUsedBytes"`
	OperatingSystem   string              `json:"operatingSystem"`
	QemuVersion       *string             `json:"qemuVersion,omitempty"`
	StorageTotalBytes *int64              `json:"storageTotalBytes,omitempty"`
	StorageUsedBytes  *int64              `json:"storageUsedBytes,omitempty"`
	UptimeSeconds     int                 `json:"uptimeSeconds"`
	Virtualization    *HostVirtualization `json:"virtualization,omitempty"`
}

// HostBridge defines model for HostBridge.
type HostBridge struct {
	Active bool   `json:"active"`
	Name   string `json:"name"`
}

// HostBridgeList defines model for HostBridgeList.
type HostBridgeList struct {
	Items []HostBridge `json:"items"`
	Total int          `json:"total"`
}

// HostVirtualization defines model for HostVirtualization.
type HostVirtualization struct {
	KvmEnabled *bool `json:"kvmEnabled,omitempty"`
}

// Iso defines model for Iso.
type Iso struct {
	FileName   string     `json:"fileName"`
	Id         string     `json:"id"`
	SizeBytes  int64      `json:"sizeBytes"`
	UploadedAt *time.Time `json:"uploadedAt,omitempty"`
}

// IsoList defines model for IsoList.
type IsoList struct {
	Items []Iso `json:"items"`
	Total int   `json:"total"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresInSeconds int `json:"expiresInSeconds"`

	// Token JWT bearer token
	Token     string `json:"token"`
	TokenType string `json:"tokenType"`
	User      User   `json:"user"`
}

// Network defines model for Network.
type Network struct {
	Autostart   bool         `json:"autostart"`
	Bridge      *string      `json:"bridge"`
	DhcpEnabled bool         `json:"dhcpEnabled"`
	DomainName  *string      `json:"domainName"`
	Id          string       `json:"id"`
	IpAddress   *string      `json:"ipAddress"`
	IpPrefix    *int         `json:"ipPrefix"`
	Mode        *NetworkMode `json:"mode,omitempty"`
	Name        string       `json:"name"`
	State       NetworkState `json:"state"`
}

// NetworkMode defines model for Network.Mode.
type NetworkMode string

// NetworkState defines model for Network.State.
type NetworkState string

// NetworkCreate defines model for NetworkCreate.
type NetworkCreate struct {
	Autostart *bool `json:"autostart"`

	// BridgeName Host bridge to attach to (required when mode is bridge).
	BridgeName *string `json:"bridgeName"`

	// Cidr Subnet for nat/isolated modes (required for those modes).
	Cidr        *string           `json:"cidr"`
	DhcpEnabled *bool             `json:"dhcpEnabled"`
	Mode        NetworkCreateMode `json:"mode"`
	Name        string            `json:"name"`
}

// NetworkCreateMode defines model for NetworkCreate.Mode.
type NetworkCreateMode string

// NetworkInterface defines model for NetworkInterface.
type NetworkInterface struct {
	IpAddress  *string               `json:"ipAddress,omitempty"`
	MacAddress *string               `json:"macAddress,omitempty"`
	Model      NetworkInterfaceModel `json:"model"`
	Name       string                `json:"name"`
	Network    *string               `json:"network,omitempty"`
}

// NetworkInterfaceModel defines model for NetworkInterface.Model.
type NetworkInterfaceModel string

// NetworkList defines model for NetworkList.
type NetworkList struct {
	Items []Network `json:"items"`
	Total int       `json:"total"`
}

// NetworkUpdate Fields left null keep their current value.
type NetworkUpdate struct {
	Autostart *bool `json:"autostart"`

	// BridgeName Host bridge to attach to (required when mode is bridge).
	BridgeName *string `json:"bridgeName"`

	// Cidr Subnet for nat/isolated modes (required for those modes).
	Cidr        *string            `json:"cidr"`
	DhcpEnabled *bool              `json:"dhcpEnabled"`
	Mode        *NetworkUpdateMode `json:"mode,omitempty"`
}

// NetworkUpdateMode defines model for NetworkUpdate.Mode.
type NetworkUpdateMode string

// PerformanceProfile Performance-oriented settings applied to the domain XML at creation,
// as detected from the domain (null for VMs created before profiles
// existed).
type PerformanceProfile struct {
	// Cache Disk cache mode applied.
	Cache *PerformanceProfileCache `json:"cache,omitempty"`

	// CpuMode `<cpu mode>` applied. host-passthrough gives best performance but limits live migration between hosts with different CPUs (multi-host phase concern).
	CpuMode *PerformanceProfileCpuMode `json:"cpuMode,omitempty"`

	// DiskBus Disk bus applied (virtio-scsi for linux/windows profiles, SATA for other).
	DiskBus *PerformanceProfileDiskBus `json:"diskBus,omitempty"`

	// HypervEnlightenments Hyper-V enlightenments actually present in the domain XML (only
	// for `windows`; only the ones supported by the host's
	// QEMU/libvirt, as detected from domain capabilities).
	HypervEnlightenments *[]string `json:"hypervEnlightenments,omitempty"`

	// IoThreads Number of iothreads dedicated to the SCSI controller (0/absent when not applied, e.g. the `other` profile).
	IoThreads *int `json:"ioThreads"`

	// NicModel Network adapter model applied (null for VMs created before this was recorded).
	NicModel *PerformanceProfileNicModel `json:"nicModel"`
}

// PerformanceProfileCache Disk cache mode applied.
type PerformanceProfileCache string

// PerformanceProfileCpuMode `<cpu mode>` applied. host-passthrough gives best performance but limits live migration between hosts with different CPUs (multi-host phase concern).
type PerformanceProfileCpuMode string

// PerformanceProfileDiskBus Disk bus applied (virtio-scsi for linux/windows profiles, SATA for other).
type PerformanceProfileDiskBus string

// PerformanceProfileNicModel Network adapter model applied (null for VMs created before this was recorded).
type PerformanceProfileNicModel string

// Readiness defines model for Readiness.
type Readiness struct {
	Hypervisor ReadinessHypervisor `json:"hypervisor"`
	Status     ReadinessStatus     `json:"status"`
}

// ReadinessHypervisor defines model for Readiness.Hypervisor.
type ReadinessHypervisor string

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// StoragePool defines model for StoragePool.
type StoragePool struct {
	AllocationBytes int64            `json:"allocationBytes"`
	Autostart       *bool            `json:"autostart,omitempty"`
	AvailableBytes  int64            `json:"availableBytes"`
	CapacityBytes   int64            `json:"capacityBytes"`
	Id              string           `json:"id"`
	Name            string           `json:"name"`
	State           StoragePoolState `json:"state"`
	TargetPath      *string          `json:"targetPath"`
	Type            StoragePoolType  `json:"type"`
}

// StoragePoolState defines model for StoragePool.State.
type StoragePoolState string

// StoragePoolType defines model for StoragePool.Type.
type StoragePoolType string

// StoragePoolCreate defines model for StoragePoolCreate.
type StoragePoolCreate struct {
	Autostart *bool `json:"autostart,omitempty"`

	// IsoLibrary When true
	IsoLibrary *bool `json:"isoLibrary,omitempty"`

	// Name Same rules as resource ids (a-z0-9._-
	Name string `json:"name"`

	// TargetPath Absolute host path; created if missing
	TargetPath string `json:"targetPath"`

	// Type Only directory pools are supported for now
	Type *StoragePoolCreateType `json:"type,omitempty"`
}

// StoragePoolCreateType Only directory pools are supported for now
type StoragePoolCreateType string

// StoragePoolList defines model for StoragePoolList.
type StoragePoolList struct {
	Items []StoragePool `json:"items"`
	Total int           `json:"total"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	Password string `json:"password"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int       `json:"id"`
	Role      UserRole  `json:"role"`
	Username  string    `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Items []User `json:"items"`
	Total int    `json:"total"`
}

// VMState - running: powered on and operational
// - stopped: powered off
// - shutting-down: graceful shutdown in progress
// - starting: power-on in progress
type VMState string

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	BootTime  *time.Time `json:"bootTime"`
	Disks     []Disk     `json:"disks"`
	Id        string     `json:"id"`
	IpAddress *string    `json:"ipAddress"`

	// IsoId Filename of the ISO currently attached as install media (CD-ROM), if any.
	IsoId       *string `json:"isoId"`
	MemoryBytes int64   `json:"memoryBytes"`

	// Metrics Point-in-time resource utilization of a running virtual machine. The whole object is absent while the VM is not running. Individual fields are null when the host cannot report them (e.g. no balloon driver / guest agent, or a first sample with no previous sample to diff against). Values are computed by the hypervisor provider, which is allowed to keep a short-lived sampling cache per VM.
	Metrics           *VmMetrics         `json:"metrics,omitempty"`
	Name              string             `json:"name"`
	NetworkInterfaces []NetworkInterface `json:"networkInterfaces"`
	Os                *string            `json:"os,omitempty"`

	// OsType Guest OS family detected from the domain XML (presence of Hyper-V
	// enlightenments implies `windows`; VMs created before profiles
	// existed may report `null`).
	OsType *VirtualMachineOsType `json:"osType"`

	// PerformanceProfile Performance-oriented settings applied to the domain XML at creation,
	// as detected from the domain (null for VMs created before profiles
	// existed).
	PerformanceProfile *PerformanceProfile `json:"performanceProfile,omitempty"`

	// State - running: powered on and operational
	// - stopped: powered off
	// - shutting-down: graceful shutdown in progress
	// - starting: power-on in progress
	State         VMState `json:"state"`
	UptimeSeconds *int    `json:"uptimeSeconds"`
	Vcpus         int     `json:"vcpus"`

	// Warnings Non-fatal notices, populated only in the create response (e.g. a
	// Windows VM created without a VirtIO drivers ISO). Absent/null on
	// reads.
	Warnings *[]string `json:"warnings"`
}

// VirtualMachineOsType Guest OS family detected from the domain XML (presence of Hyper-V
// enlightenments implies `windows`; VMs created before profiles
// existed may report `null`).
type VirtualMachineOsType string

// VirtualMachineCreate defines model for VirtualMachineCreate.
type VirtualMachineCreate struct {
	Disk DiskCreate `json:"disk"`

	// IsoId Optional ISO from the library to attach as install media (CD-ROM, first boot device).
	IsoId       *string `json:"isoId"`
	MemoryBytes int64   `json:"memoryBytes"`
	Name        string  `json:"name"`
	NetworkId   *string `json:"networkId,omitempty"`

	// NicModel Network adapter model. Omitted, it follows the `osType` profile:
	// `virtio` for linux/windows, `e1000e` for other.
	//
	// `virtio` is the fastest but needs a driver in the guest. Linux has
	// it in-tree; **Windows does not** — the NIC stays unusable (device
	// error 43 or an unknown Ethernet controller) until NetKVM is
	// installed from the VirtIO drivers ISO. Pick `e1000e` for a Windows
	// guest that must have network on first boot, or `rtl8139` for very
	// old guests without an e1000e driver.
	NicModel *VirtualMachineCreateNicModel `json:"nicModel"`

	// OsType Guest operating system family, selects the performance profile
	// applied to the domain XML (see endpoint description).
	OsType *VirtualMachineCreateOsType `json:"osType,omitempty"`

	// Start Power on immediately after creation.
	Start *bool `json:"start,omitempty"`
	Vcpus int   `json:"vcpus"`

	// VirtioDriversIsoId Optional VirtIO drivers ISO from the library (e.g.
	// `virtio-win-0.1.266.iso`), attached as a second SATA CD-ROM for
	// Windows installations. Only meaningful when `osType` is `windows`;
	// ignored otherwise. Without it the Windows installer cannot see the
	// virtio-scsi disk unless drivers are loaded from another source.
	VirtioDriversIsoId *string `json:"virtioDriversIsoId"`
}

// VirtualMachineCreateNicModel Network adapter model. Omitted, it follows the `osType` profile:
// `virtio` for linux/windows, `e1000e` for other.
//
// `virtio` is the fastest but needs a driver in the guest. Linux has
// it in-tree; **Windows does not** — the NIC stays unusable (device
// error 43 or an unknown Ethernet controller) until NetKVM is
// installed from the VirtIO drivers ISO. Pick `e1000e` for a Windows
// guest that must have network on first boot, or `rtl8139` for very
// old guests without an e1000e driver.
type VirtualMachineCreateNicModel string

// VirtualMachineCreateOsType Guest operating system family, selects the performance profile
// applied to the domain XML (see endpoint description).
type VirtualMachineCreateOsType string

// VirtualMachineList defines model for VirtualMachineList.
type VirtualMachineList struct {
	Items []VirtualMachine `json:"items"`
	Total int              `json:"total"`
}

// VirtualMachineUpdate Partial update of a VM's settings. Only provided fields are changed. vCPU and memory require the VM to be stopped. For isoId, a filename attaches/swaps the install media and an empty string detaches it.
type VirtualMachineUpdate struct {
	// IsoId ISO filename from the library to attach/swap; an empty string detaches the current ISO.
	IsoId       *string `json:"isoId,omitempty"`
	MemoryBytes *int64  `json:"memoryBytes,omitempty"`

	// NetworkId Moves the VM's network interface to another virtual network.
	// Requires the VM to be stopped (applied to the persistent config).
	NetworkId *string `json:"networkId,omitempty"`
	Vcpus     *int    `json:"vcpus,omitempty"`
}

// VmMetrics Point-in-time resource utilization of a running virtual machine. The whole object is absent while the VM is not running. Individual fields are null when the host cannot report them (e.g. no balloon driver / guest agent, or a first sample with no previous sample to diff against). Values are computed by the hypervisor provider, which is allowed to keep a short-lived sampling cache per VM.
type VmMetrics struct {
	// CpuPercent CPU utilization relative to the VM's allocated vCPUs.
	CpuPercent *float32 `json:"cpuPercent"`

	// MemoryUsedBytes Guest memory currently in use. Null unless the guest balloon driver or agent reports it.
	MemoryUsedBytes *int64 `json:"memoryUsedBytes"`

	// NetworkRxBytesPerSecond Inbound network throughput across all interfaces. Null until a second sample is available to compute a rate.
	NetworkRxBytesPerSecond *int64 `json:"networkRxBytesPerSecond"`

	// NetworkTxBytesPerSecond Outbound network throughput across all interfaces. Null until a second sample is available to compute a rate.
	NetworkTxBytesPerSecond *int64 `json:"networkTxBytesPerSecond"`

	// SampledAt When the underlying sample was taken.
	SampledAt time.Time `json:"sampledAt"`
}

// ResourceID defines model for ResourceID.
type ResourceID = string

// ScheduleId defines model for ScheduleId.
type ScheduleId = string

// UserId defines model for UserId.
type UserId = int

// VMId defines model for VMId.
type VMId = string

// BackupNotFound defines model for BackupNotFound.
type BackupNotFound = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// ScheduleNotFound defines model for ScheduleNotFound.
type ScheduleNotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// VMInvalidState defines model for VMInvalidState.
type VMInvalidState = Error

// VMNotFound defines model for VMNotFound.
type VMNotFound = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// UploadIsoMultipartBody defines parameters for UploadIso.
type UploadIsoMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// DeleteVirtualMachineParams defines parameters for DeleteVirtualMachine.
type DeleteVirtualMachineParams struct {
	// DeleteDisks Also delete the VM's disk volumes from the storage pool.
	DeleteDisks *bool `form:"deleteDisks,omitempty" json:"deleteDisks,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangeOwnPasswordJSONRequestBody defines body for ChangeOwnPassword for application/json ContentType.
type ChangeOwnPasswordJSONRequestBody = ChangePasswordRequest

// CreateBackupScheduleJSONRequestBody defines body for CreateBackupSchedule for application/json ContentType.
type CreateBackupScheduleJSONRequestBody = BackupScheduleCreate

// UpdateBackupScheduleJSONRequestBody defines body for UpdateBackupSchedule for application/json ContentType.
type UpdateBackupScheduleJSONRequestBody = BackupScheduleUpdate

// CreateNetworkJSONRequestBody defines body for CreateNetwork for application/json ContentType.
type CreateNetworkJSONRequestBody = NetworkCreate

// UpdateNetworkJSONRequestBody defines body for UpdateNetwork for application/json ContentType.
type UpdateNetworkJSONRequestBody = NetworkUpdate

// UploadIsoMultipartRequestBody defines body for UploadIso for multipart/form-data ContentType.
type UploadIsoMultipartRequestBody UploadIsoMultipartBody

// CreateStoragePoolJSONRequestBody defines body for CreateStoragePool for application/json ContentType.
type CreateStoragePoolJSONRequestBody = StoragePoolCreate

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// ResetUserPasswordJSONRequestBody defines body for ResetUserPassword for application/json ContentType.
type ResetUserPasswordJSONRequestBody = UpdatePasswordRequest

// CreateVirtualMachineJSONRequestBody defines body for CreateVirtualMachine for application/json ContentType.
type CreateVirtualMachineJSONRequestBody = VirtualMachineCreate

// UpdateVirtualMachineJSONRequestBody defines body for UpdateVirtualMachine for application/json ContentType.
type UpdateVirtualMachineJSONRequestBody = VirtualMachineUpdate

// CreateVMBackupJSONRequestBody defines body for CreateVMBackup for application/json ContentType.
type CreateVMBackupJSONRequestBody = BackupCreate
