// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DiskBus.
const (
	DiskBusSata   DiskBus = "sata"
	DiskBusScsi   DiskBus = "scsi"
	DiskBusVirtio DiskBus = "virtio"
)

// Defines values for DiskFormat.
const (
	DiskFormatQcow2 DiskFormat = "qcow2"
	DiskFormatRaw   DiskFormat = "raw"
)

// Defines values for DiskCreateFormat.
const (
	DiskCreateFormatQcow2 DiskCreateFormat = "qcow2"
	DiskCreateFormatRaw   DiskCreateFormat = "raw"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Defines values for NetworkState.
const (
	NetworkStateActive   NetworkState = "active"
	NetworkStateInactive NetworkState = "inactive"
)

// Defines values for NetworkInterfaceModel.
const (
	NetworkInterfaceModelE1000   NetworkInterfaceModel = "e1000"
	NetworkInterfaceModelRtl8139 NetworkInterfaceModel = "rtl8139"
	NetworkInterfaceModelVirtio  NetworkInterfaceModel = "virtio"
)

// Defines values for ReadinessHypervisor.
const (
	ReadinessHypervisorReady       ReadinessHypervisor = "ready"
	ReadinessHypervisorUnavailable ReadinessHypervisor = "unavailable"
)

// Defines values for ReadinessStatus.
const (
	ReadinessStatusNotReady ReadinessStatus = "not-ready"
	ReadinessStatusReady    ReadinessStatus = "ready"
)

// Defines values for StoragePoolState.
const (
	StoragePoolStateActive   StoragePoolState = "active"
	StoragePoolStateInactive StoragePoolState = "inactive"
)

// Defines values for StoragePoolType.
const (
	StoragePoolTypeDir   StoragePoolType = "dir"
	StoragePoolTypeDisk  StoragePoolType = "disk"
	StoragePoolTypeFs    StoragePoolType = "fs"
	StoragePoolTypeIscsi StoragePoolType = "iscsi"
	StoragePoolTypeLvm   StoragePoolType = "lvm"
	StoragePoolTypeNetfs StoragePoolType = "netfs"
	StoragePoolTypeOther StoragePoolType = "other"
	StoragePoolTypeRbd   StoragePoolType = "rbd"
	StoragePoolTypeZfs   StoragePoolType = "zfs"
)

// Defines values for StoragePoolCreateType.
const (
	StoragePoolCreateTypeDir StoragePoolCreateType = "dir"
)

// Defines values for VMState.
const (
	VMStateError        VMState = "error"
	VMStatePaused       VMState = "paused"
	VMStateRunning      VMState = "running"
	VMStateShuttingDown VMState = "shutting-down"
	VMStateStarting     VMState = "starting"
	VMStateStopped      VMState = "stopped"
)

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Features       CapabilitiesFeatures       `json:"features"`
	Storage        CapabilitiesStorage        `json:"storage"`
	Virtualization CapabilitiesVirtualization `json:"virtualization"`
}

// CapabilitiesFeatures defines model for CapabilitiesFeatures.
type CapabilitiesFeatures struct {
	Backup    bool `json:"backup"`
	CloudInit bool `json:"cloudInit"`
	Migration bool `json:"migration"`
}

// CapabilitiesStorage defines model for CapabilitiesStorage.
type CapabilitiesStorage struct {
	Qcow2     bool `json:"qcow2"`
	Raw       bool `json:"raw"`
	Snapshots bool `json:"snapshots"`
}

// CapabilitiesVirtualization defines model for CapabilitiesVirtualization.
type CapabilitiesVirtualization struct {
	Kvm  bool `json:"kvm"`
	Uefi bool `json:"uefi"`
}

// Cpu defines model for Cpu.
type Cpu struct {
	Cores        int      `json:"cores"`
	Model        string   `json:"model"`
	Threads      int      `json:"threads"`
	UsagePercent *float32 `json:"usagePercent,omitempty"`
}

// Disk defines model for Disk.
type Disk struct {
	Bus       *DiskBus   `json:"bus,omitempty"`
	Format    DiskFormat `json:"format"`
	Name      string     `json:"name"`
	SizeBytes int64      `json:"sizeBytes"`
}

// DiskBus defines model for Disk.Bus.
type DiskBus string

// DiskFormat defines model for Disk.Format.
type DiskFormat string

// DiskCreate defines model for DiskCreate.
type DiskCreate struct {
	Format    *DiskCreateFormat `json:"format,omitempty"`
	PoolId    string            `json:"poolId"`
	SizeBytes int64             `json:"sizeBytes"`
}

// DiskCreateFormat defines model for DiskCreate.Format.
type DiskCreateFormat string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code      string `json:"code"`
		Message   string `json:"message"`
		RequestId string `json:"requestId"`
	} `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Host defines model for Host.
type Host struct {
	Cpu               Cpu                 `json:"cpu"`
	Hostname          string              `json:"hostname"`
	Kernel            string              `json:"kernel"`
	LibvirtVersion    *string             `json:"libvirtVersion,omitempty"`
	MemoryTotalBytes  int64               `json:"memoryTotalBytes"`
	MemoryUsedBytes   int64               `json:"memoryUsedBytes"`
	OperatingSystem   string              `json:"operatingSystem"`
	QemuVersion       *string             `json:"qemuVersion,omitempty"`
	StorageTotalBytes *int64              `json:"storageTotalBytes,omitempty"`
	StorageUsedBytes  *int64              `json:"storageUsedBytes,omitempty"`
	UptimeSeconds     int                 `json:"uptimeSeconds"`
	Virtualization    *HostVirtualization `json:"virtualization,omitempty"`
}

// HostVirtualization defines model for HostVirtualization.
type HostVirtualization struct {
	KvmEnabled *bool `json:"kvmEnabled,omitempty"`
}

// Iso defines model for Iso.
type Iso struct {
	FileName   string     `json:"fileName"`
	Id         string     `json:"id"`
	SizeBytes  int64      `json:"sizeBytes"`
	UploadedAt *time.Time `json:"uploadedAt,omitempty"`
}

// IsoList defines model for IsoList.
type IsoList struct {
	Items []Iso `json:"items"`
	Total int   `json:"total"`
}

// Network defines model for Network.
type Network struct {
	Autostart   bool         `json:"autostart"`
	Bridge      *string      `json:"bridge"`
	DhcpEnabled bool         `json:"dhcpEnabled"`
	DomainName  *string      `json:"domainName"`
	Id          string       `json:"id"`
	IpAddress   *string      `json:"ipAddress"`
	IpPrefix    *int         `json:"ipPrefix"`
	Name        string       `json:"name"`
	State       NetworkState `json:"state"`
}

// NetworkState defines model for Network.State.
type NetworkState string

// NetworkInterface defines model for NetworkInterface.
type NetworkInterface struct {
	IpAddress  *string               `json:"ipAddress,omitempty"`
	MacAddress *string               `json:"macAddress,omitempty"`
	Model      NetworkInterfaceModel `json:"model"`
	Name       string                `json:"name"`
	Network    *string               `json:"network,omitempty"`
}

// NetworkInterfaceModel defines model for NetworkInterface.Model.
type NetworkInterfaceModel string

// NetworkList defines model for NetworkList.
type NetworkList struct {
	Items []Network `json:"items"`
	Total int       `json:"total"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Hypervisor ReadinessHypervisor `json:"hypervisor"`
	Status     ReadinessStatus     `json:"status"`
}

// ReadinessHypervisor defines model for Readiness.Hypervisor.
type ReadinessHypervisor string

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// StoragePool defines model for StoragePool.
type StoragePool struct {
	AllocationBytes int64            `json:"allocationBytes"`
	Autostart       *bool            `json:"autostart,omitempty"`
	AvailableBytes  int64            `json:"availableBytes"`
	CapacityBytes   int64            `json:"capacityBytes"`
	Id              string           `json:"id"`
	Name            string           `json:"name"`
	State           StoragePoolState `json:"state"`
	TargetPath      *string          `json:"targetPath"`
	Type            StoragePoolType  `json:"type"`
}

// StoragePoolState defines model for StoragePool.State.
type StoragePoolState string

// StoragePoolType defines model for StoragePool.Type.
type StoragePoolType string

// StoragePoolCreate defines model for StoragePoolCreate.
type StoragePoolCreate struct {
	Autostart *bool `json:"autostart,omitempty"`

	// Name Same rules as resource ids (a-z0-9._-
	Name string `json:"name"`

	// TargetPath Absolute host path; created if missing
	TargetPath string `json:"targetPath"`

	// Type Only directory pools are supported for now
	Type *StoragePoolCreateType `json:"type,omitempty"`
}

// StoragePoolCreateType Only directory pools are supported for now
type StoragePoolCreateType string

// StoragePoolList defines model for StoragePoolList.
type StoragePoolList struct {
	Items []StoragePool `json:"items"`
	Total int           `json:"total"`
}

// VMState - running: powered on and operational
// - stopped: powered off
// - shutting-down: graceful shutdown in progress
// - starting: power-on in progress
type VMState string

// VirtualMachine defines model for VirtualMachine.
type VirtualMachine struct {
	BootTime          *time.Time         `json:"bootTime"`
	Disks             []Disk             `json:"disks"`
	Id                string             `json:"id"`
	IpAddress         *string            `json:"ipAddress"`
	MemoryBytes       int64              `json:"memoryBytes"`
	Name              string             `json:"name"`
	NetworkInterfaces []NetworkInterface `json:"networkInterfaces"`
	Os                *string            `json:"os,omitempty"`

	// State - running: powered on and operational
	// - stopped: powered off
	// - shutting-down: graceful shutdown in progress
	// - starting: power-on in progress
	State         VMState `json:"state"`
	UptimeSeconds *int    `json:"uptimeSeconds"`
	Vcpus         int     `json:"vcpus"`
}

// VirtualMachineCreate defines model for VirtualMachineCreate.
type VirtualMachineCreate struct {
	Disk DiskCreate `json:"disk"`

	// IsoId Optional ISO from the library to attach as install media (CD-ROM, first boot device).
	IsoId       *string `json:"isoId"`
	MemoryBytes int64   `json:"memoryBytes"`
	Name        string  `json:"name"`
	NetworkId   *string `json:"networkId,omitempty"`

	// Start Power on immediately after creation.
	Start *bool `json:"start,omitempty"`
	Vcpus int   `json:"vcpus"`
}

// VirtualMachineList defines model for VirtualMachineList.
type VirtualMachineList struct {
	Items []VirtualMachine `json:"items"`
	Total int              `json:"total"`
}

// ResourceID defines model for ResourceID.
type ResourceID = string

// VMId defines model for VMId.
type VMId = string

// InternalError defines model for InternalError.
type InternalError = Error

// VMInvalidState defines model for VMInvalidState.
type VMInvalidState = Error

// VMNotFound defines model for VMNotFound.
type VMNotFound = Error

// UploadIsoMultipartBody defines parameters for UploadIso.
type UploadIsoMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadIsoMultipartRequestBody defines body for UploadIso for multipart/form-data ContentType.
type UploadIsoMultipartRequestBody UploadIsoMultipartBody

// CreateStoragePoolJSONRequestBody defines body for CreateStoragePool for application/json ContentType.
type CreateStoragePoolJSONRequestBody = StoragePoolCreate

// CreateVirtualMachineJSONRequestBody defines body for CreateVirtualMachine for application/json ContentType.
type CreateVirtualMachineJSONRequestBody = VirtualMachineCreate
